language: generic

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - CTAPIPE_VERSION=master
        - CTAPIPE_EXTRA_VERSION=master
    - os: linux
      python: 3.7
      env:
        - PYTHON_VERSION=3.7
        - CTAPIPE_VERSION=master
        - CTAPIPE_EXTRA_VERSION=master
    # - os: osx
    #   python: 3.6
    #   env:
    #     - PYTHON_VERSION=3.6
    # - os: osx
    #   python: 3.7
    #   env:
    #     - PYTHON_VERSION=3.7



before_install:
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a # Useful for debugging any issues with conda

install:
    - conda env create -n cta-dev python=$PYTHON_VERSION -f py${PYTHON_VERSION}_env.yaml
    - conda activate cta-dev
    - ulimit -s 16000  # increase stack size limit, for libhessio
    - pip install travis-sphinx
    - pip install codecov
    - pip install .

#script:
#    - pytest --cov=ctapipe_io_mchdf5
    #- travis-sphinx -v --outdir=docbuild build --source=docs/

after_script:
    - conda deactivate

after_success:
    - travis-sphinx -v --outdir=docbuild deploy
    - codecov
